In [1]:
import yfinance as yf

In [3]:
data = yf.Ticker("AAPL").history(period='5y')

In [4]:
data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-02-22 00:00:00-05:00,124.681168,126.346707,122.333842,122.723442,103916400,0.0,0.0
2021-02-23 00:00:00-05:00,120.541685,123.414969,115.311327,122.587074,158273000,0.0,0.0
2021-02-24 00:00:00-05:00,121.691013,122.294885,119.051486,122.090347,111039900,0.0,0.0
2021-02-25 00:00:00-05:00,121.437765,123.171476,117.405424,117.843719,148199500,0.0,0.0
2021-02-26 00:00:00-05:00,119.402098,121.603330,118.048245,118.106689,164560400,0.0,0.0
...,...,...,...,...,...,...,...
2026-02-13 00:00:00-05:00,262.010010,262.230011,255.449997,255.779999,56290700,0.0,0.0
2026-02-17 00:00:00-05:00,258.049988,266.290009,255.539993,263.880005,58469100,0.0,0.0
2026-02-18 00:00:00-05:00,263.600006,266.820007,262.450012,264.350006,34203300,0.0,0.0
2026-02-19 00:00:00-05:00,262.600006,264.480011,260.049988,260.579987,30845300,0.0,0.0
2026-02-20 00:00:00-05:00,258.970001,264.750000,258.160004,264.579987,42044900,0.0,0.0

In [10]:
import pandas_ta_classic as ta

# simple moving average
data.ta.sma(length=50)[49:]

Date
2021-05-03 00:00:00-04:00    123.173624
2021-05-04 00:00:00-04:00    123.209662
2021-05-05 00:00:00-04:00    123.253298
2021-05-06 00:00:00-04:00    123.338814
2021-05-07 00:00:00-04:00    123.522728
                                ...
2026-02-13 00:00:00-05:00    267.250229
2026-02-17 00:00:00-05:00    266.850142
2026-02-18 00:00:00-05:00    266.528390
2026-02-19 00:00:00-05:00    266.169602
2026-02-20 00:00:00-05:00    265.908597
Name: SMA_50, Length: 1207, dtype: float64

In [13]:
ta.sma(data.Volume, lenght=50)[49: ]

Date
2021-05-03 00:00:00-04:00    90364000.0
2021-05-04 00:00:00-04:00    94639240.0
2021-05-05 00:00:00-04:00    96154620.0
2021-05-06 00:00:00-04:00    95510800.0
2021-05-07 00:00:00-04:00    95542380.0
                                ...
2026-02-13 00:00:00-05:00    60058410.0
2026-02-17 00:00:00-05:00    58513980.0
2026-02-18 00:00:00-05:00    55494840.0
2026-02-19 00:00:00-05:00    49524800.0
2026-02-20 00:00:00-05:00    48431550.0
Name: SMA_10, Length: 1207, dtype: float64

In [14]:
# exponential moving average
ta.ema(data.Open, lenght = 20)[19:]

Date
2021-03-19 00:00:00-04:00    119.222779
2021-03-22 00:00:00-04:00    118.855160
2021-03-23 00:00:00-04:00    119.085656
2021-03-24 00:00:00-04:00    119.183922
2021-03-25 00:00:00-04:00    118.683468
                                ...
2026-02-13 00:00:00-05:00    269.780987
2026-02-17 00:00:00-05:00    267.648078
2026-02-18 00:00:00-05:00    266.912065
2026-02-19 00:00:00-05:00    266.128054
2026-02-20 00:00:00-05:00    264.826590
Name: EMA_10, Length: 1237, dtype: float64

In [20]:
# relative strength index
data.ta.rsi(length=14)[14:]

Date
2021-03-12 00:00:00-05:00    44.681858
2021-03-15 00:00:00-04:00    51.580702
2021-03-16 00:00:00-04:00    54.819720
2021-03-17 00:00:00-04:00    52.867203
2021-03-18 00:00:00-04:00    44.044824
                               ...
2026-02-13 00:00:00-05:00    39.585494
2026-02-17 00:00:00-05:00    48.607349
2026-02-18 00:00:00-05:00    49.082488
2026-02-19 00:00:00-05:00    45.452492
2026-02-20 00:00:00-05:00    49.702836
Name: RSI_14, Length: 1242, dtype: float64

In [21]:
data.ta.macd(fast=8, slow=21)

                           MACD_8_21_9  MACDh_8_21_9  MACDs_8_21_9
Date
2021-02-22 00:00:00-05:00          NaN           NaN           NaN
2021-02-23 00:00:00-05:00          NaN           NaN           NaN
2021-02-24 00:00:00-05:00          NaN           NaN           NaN
2021-02-25 00:00:00-05:00          NaN           NaN           NaN
2021-02-26 00:00:00-05:00          NaN           NaN           NaN
...                                ...           ...           ...
2026-02-13 00:00:00-05:00     1.187052     -1.373855      2.560906
2026-02-17 00:00:00-05:00     0.699526     -1.489104      2.188630
2026-02-18 00:00:00-05:00     0.402397     -1.428987      1.831384
2026-02-19 00:00:00-05:00    -0.310877     -1.713809      1.402931
2026-02-20 00:00:00-05:00    -0.283679     -1.349289      1.065609

[1256 rows x 3 columns]